### ISSUE TITLE
ssh mode with key read: Connection reset by peer

### ISSUE THREAD

**Issue by anjoweichbrodt** [pschiffe/docker-borg#12]
Hi, I attempt to use docker-borg unsuccessfully with ssh key authentication:

```
docker run \
  -e SSHFS='backupuser@remotemachine:/home/backupuser
  -e SSHFS_IDENTITY_FILE=/root/ssh-key/key \
  -e BACKUP_DIRS=/borg/data \
  -e PRUNE=1 \
  -v borg-config:/root \
  --cap-add SYS_ADMIN --device /dev/fuse --security-opt label:disable --security-opt apparmor:unconfined \
  --name borg-backup \
  pschiffe/borg
```
I get the error message `read: Connection reset by peer`

SSH and SSHFS run separately, do the ssh key authentication properly on the remote machine.

Many thanks for your help.

**Comment by pschiffe** [comment]
hi @anjoweichbrodt ,
you are missing `'` on this line `-e SSHFS='backupuser@remotemachine:/home/backupuser` (if it's not just copy-paste error)

Could you try to run bash in the container and ssh manually from it?

```
docker run \
  -e SSHFS='backupuser@remotemachine:/home/backupuser'
  -e SSHFS_IDENTITY_FILE=/root/ssh-key/key \
  -e BACKUP_DIRS=/borg/data \
  -e PRUNE=1 \
  -v borg-config:/root \
  --cap-add SYS_ADMIN --device /dev/fuse --security-opt label:disable --security-opt apparmor:unconfined \
  --name borg-backup \
  pschiffe/borg bash
```
then `ssh backupuser@remotemachine`

Provide output, potentially you can get more verbose output with `-vvvv` options.

**Comment by anjoweichbrodt** [comment]
Many thanks for your prompt reply. Indeed, the `'` was a copy-paste error.

Running docker in debug mode with `docker -D` sadly does not give any more information.

`docker logs borg-backup` returns the preceding error messages: `read: Connection reset by peer`

**Comment by pschiffe** [comment]
Try to do what I wrote in the previous comment, notice the last line: `pschiffe/borg bash`, but yeah, you also need to specify `-it` for interactive shell:
```
docker run \
  -e SSHFS='backupuser@remotemachine:/home/backupuser'
  -e SSHFS_IDENTITY_FILE=/root/ssh-key/key \
  -e BACKUP_DIRS=/borg/data \
  -e PRUNE=1 \
  -v borg-config:/root \
  --cap-add SYS_ADMIN --device /dev/fuse --security-opt label:disable --security-opt apparmor:unconfined \
  --name borg-backup \
  -it \
  pschiffe/borg bash
```
Then you can run commands in the container environment, and try just the ssh command.

**Comment by anjoweichbrodt** [comment]
My bad.
Indeed, getting into the interactive shell, I was requested to accept the fingerprint:

```Are you sure you want to continue connecting (yes/no/[fingerprint])? yes```

... and it worked. Many thanks for your help.
