### ISSUE TITLE
Creating SSHFS fails when using SSHFS_PASSWORD with special characters (such as #)

### ISSUE THREAD

**Issue by jonasdedden** [pschiffe/docker-borg#16]
In the entrypoint script `borg-backup.sh` there are two possible ways to mount the SSHFS, either by using an identity file or explicitly stating a password.

Latter has some problems with passwords containing characters such as "#":

`SSHFS_PASSWORD="echo ${SSHFS_PASSWORD} |"`
`eval "${SSHFS_PASSWORD} sshfs ${SSHFS} /mnt/sshfs ${SSHFS_IDENTITY_FILE} ${SSHFS_PASSWORD_OPT}"`

This would evaluate to:

`echo XXXX#YYYY | sshfs ...` 

leading to just 'XXXX' echoed into nowhere and the rest of the line interpreted as a comment.

 I believe it should be `SSHFS_PASSWORD="echo \"${SSHFS_PASSWORD}\" |"` to fix the issue, e.g. adding some quotes here around `${SSHFS_PASSWORD}`.

**Comment by pschiffe** [comment]
Hello @jonded94 and sorry for the late response. I wasn't able to reproduce your problem:
```
$ SSHFS_PASSWORD=abc#def
$ SSHFS_PASSWORD="echo ${SSHFS_PASSWORD} |"
$ eval "${SSHFS_PASSWORD} bat"
───────┬─────────────
       │ STDIN
───────┼─────────────
   1   │ abc#def
───────┴─────────────
```
But I did add a variation of your PR, just without the backslashes in https://github.com/pschiffe/docker-borg/commit/c3256b0f401a8a59b95ce693a13109f43e86a70a
Hope it helps with your problem.
