### ISSUE TITLE
Truenas Scale fuse error

### ISSUE THREAD

**Issue by d1nd141** [pschiffe/docker-borg#20]
Hi,
i'm trying to run this container in TN Scale as a Pod.
I tried with the 
SYS_ADMIN --device /dev/fuse
and without.
On truenas, i executed modprobe fuse, module is loaded (lsmod), and /dev/fuse exists on the host. 

Error:
fuse: device not found, try 'modprobe fuse' first
(no more text)

Also passing /dev/fuse as voluem does not help.

Any idea?
Thanks

**Comment by pschiffe** [comment]
You can try to run it with `--privileged` flag, just to test. Also is there any security in place, such as selinux or apparmor?

**Comment by d1nd141** [comment]
Using privileged, i receive
read: Connection reset by peer

Afaik selinux is running, but no binaries like getenforce or sestatus are installed.

**Comment by pschiffe** [comment]
You can try with `--security-opt label:disable` then, to disable selinux for the container. If that doesn't work, paste the whole docker run command here please.
