### ISSUE TITLE
Ubuntu AppArmor prevents mounting of sshfs volume in container

### ISSUE THREAD

**Issue by cortlieb** [pschiffe/docker-borg#24]
After I was able to run the docker BorgBackup Image (with the great support of @pschiffe !) on WSL (Windows Subsystem for Linux) I tried to transfer the solution to a server.
But here I got the error message
`fuse: mount failed: Permission denied`
when starting the container.

I ggogled a bit and found that others had similar issues with fuse mounts in containers. They blamed AppArmor (afaik something similar to SELinux) and recommended to use the `--security-opt apparmor:unconfined` option.
I tried that and the docker-borg image worked on the server, too.
Thought that could be good information for you, @pschiffe .

I don't know enough about AppArmor (in fact almost nothing) to tell why it works on WSL without the additional option, but not on the server. Both run the same OS (Ubuntu 22.04.4 LTS). I assume some AppArmor default setting are different between both installations.

**Comment by pschiffe** [comment]
Correct, this is already mentioned in the README - https://github.com/pschiffe/docker-borg?tab=readme-ov-file#sshfs

It really depends on your OS configuration, RHEL based systems have selinux enabled by default, then you need to specify `--security-opt label:disable` or disable selinux. Ubuntu comes with AppArmor enabled by default, so you need to use `--security-opt apparmor:unconfined` or disable AppArmor. I guess WSL is already isolated from the main OS, as it's using light virtualization so maybe they just decided to not enable AppArmor by default there, as it may be hassle for some use cases.

**Comment by cortlieb** [comment]
> Correct, this is already mentioned in the README

Oh, sorry, you're right. I looked at the top of the README and there only SELinux was mentioned. I didn't notice that AppArmor is mentioned in the SSHFS chapter.
