### ISSUE TITLE
Call `borg extract` with option `--progress` ?

### ISSUE THREAD

**Issue by cortlieb** [pschiffe/docker-borg#25]
Since restoring a Borg backup can take a while, I like to run the extract command with the option `--progress` . With this option the percentage of the already restored archive is shown.
Is there a way to configure Borg in the container to run with option `--progress`?

Christian

**Comment by pschiffe** [comment]
Updated image should be now available with `-e SHOW_PROGRESS=1` env var, can you try?

**Comment by cortlieb** [comment]
Works fine when extracting a backup!

Anyhow, when I list the available backups  I get an error message:
`/borg-backup.sh: line 95: PROGRESS: unbound variable`

Here is how I start the container:
```
docker run -it \
  -e DEBUG=0 \
  -e SSHFS='<username>@rsync.hidrive.strato.com:/users/<username>/owiot_bk' \
  -e SSHFS_IDENTITY_FILE=/root/ssh-key/id_ed25519 \
  -e SHOW_PROGRESS=0 \
  -e BORG_PASSPHRASE=<passphrase> \
  -e BORG_PARAMS='list' \
  -v /home/<username>/docker-borg/config/:/root \
  --cap-add SYS_ADMIN --device /dev/fuse --security-opt label:disable --security-opt apparmor:unconfined \
  --name borg-backup \
  pschiffe/borg
```

**Comment by pschiffe** [comment]
Thanks for the test, should be fixed now.

**Comment by cortlieb** [comment]
Yes, works fine!

Thank you for adding the feature!
