### ISSUE TITLE
borg compact executed with -e PRUNE=1?

### ISSUE THREAD

**Issue by cortlieb** [pschiffe/docker-borg#27]
I'm using your docker-image to do a backup with 
` -e PRUNE=1`

In the borg docs one can read:
> Important: Repository disk space is not freed until you run borg compact.

Does your container automatically execute `borg compact` or do i Have to do that manually, probably by using the `-e BORG_PARAMS='compact'` parameter?

Thanks
Christian

**Comment by pschiffe** [comment]
Nice find! I've added the `borg compact` command to be run after prune. Updated image should be already available in the docker hub. Cheers.

**Comment by cortlieb** [comment]
![grafik](https://github.com/user-attachments/assets/091c8064-167f-4bee-bcc0-2826bbb80fe9)
Great!
Thank you very much for the extremely quick response!
