### ISSUE TITLE
locale warning while restoring

### ISSUE THREAD

**Issue by bbigras** [pschiffe/docker-borg#3]
I got this warning while restoring a file:

> Warning: File system encoding is "ascii", extracting non-ascii filenames will not be supported.
Hint: You likely need to fix your locale setup. E.g. install locales and use: LANG=en_US.UTF-8

It's from borg https://github.com/borgbackup/borg/blob/3db27f950e901fa6fcb679962a8432bd1ed059e0/src/borg/archiver.py#L626

**Comment by pschiffe** [comment]
I've set the `LANG` env var in the image, can you try it? https://github.com/pschiffe/docker-borg/commit/20bca24adc1999488772a4968e7029b1c0a7cfab

**Comment by bbigras** [comment]
I don't have the warning anymore. Thanks.
