### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by pierreozoux** [pschiffe/docker-borg#7]
Hello!

I've been using your script (partly) for years, and I'm really happy :) Thanks a lot for your work ;)

I'm now asking for upstream to have an official image, and created [this PR](https://github.com/borgbackup/borg/pull/4372).

I copied your script and README, and mentionned your name. I hope it is fine, if not, please let me know.

If you have comments, feel free to comment there. (and close this issue.

**Comment by pschiffe** [comment]
Thank you for letting me know. It's OK.
