### ISSUE TITLE
Keep it up-to-date/add CI/CD

### ISSUE THREAD

**Issue by rugk** [pschiffe/docker-borg#9]
You should really keep your image up-to-date, possibly also add a CI to keep it up-to-date and automatically push updates.
Also GitHub provides Dependabot, though IÄm not sure it would catch these issues here…

The thing is, [your image is the most popular on Docker Hub for Borg with >500k pulls](https://hub.docker.com/r/pschiffe/borg).

E.g. here you use Fedora **31**:

https://github.com/pschiffe/docker-borg/blob/83811abba71853c2d69d26a106c246b3462abe41/Dockerfile#L1

Fedora 31 is long outdated/unmaintained, so better upgrade that…

**Comment by pschiffe** [comment]
Thanks for the notification.

**Comment by rugk** [comment]
I guess with Dependabot you may also automatically get such notifications: https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates

**Comment by pschiffe** [comment]
https://github.com/pschiffe/docker-borg/blob/master/.github/dependabot.yml
